notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

install:
 - gem install mdl
 - virtualenv -p python venv
 - source venv/bin/activate
 - pip install html5 cwltool

script:
 - set -e
 - echo 'Validate Markdown file(s)'
 - mdl -r ~MD013,~MD024,~MD046,~MD007 -g . # ignore line too long rule
 - echo 'Validate CWL file(s)'
 - cwltool --validate cwls/chksum_seqval_wf_interleaved_fq.cwl
 - cwltool --validate cwls/chksum_seqval_wf_paired_fq.cwl
